main:
  device: cuda
  style: ./src/data/starry_night_van_gogh.png
  content: ./src/data/banff-pets.png
  alpha: 2
  save_path: ./src/result/starry_banff.png
  load_codec:
    encoder_pt_path: ./src/model/weights/vgg19_encoder.pt
    decoder_pt_path: ./src/model/weights/vgg19_decoder.pt
  fourcc: DIVX
  video_writer:
    filename: ./test.mp4
    fps: 25
    frameSize: [1024, 1024]