main:
  device: cuda
  style_image: ./src/data/frozen.jpg
  content_image: ./src/data/picasso.jpg 
  encoder_pt_path: ./src/model/weights/vgg19_encoder.pt 
  decoder_pt_path: ./src/model/weights/vgg19_decoder.pt 
  alpha: 0.5 
  save_path: ./src/result/pocasso_.png 